### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by phil-r**

### CODE REVIEW

**Comment by MoOx** [comment]
Master didn't fail when it was build (I know it's 10 month ago, but semver...?).
Could you explain the motivation or this PR?

**Comment by phil-r** [comment]
Hi @MoOx , for me latest master fails with 

```
TypeError: Cannot read property 'lastVersions' of undefined
```

Also I can't find such api(`browserslist.queries.lastVersions.select(1)`) in `browserslist`

**Comment by phil-r** [comment]
@MoOx Here is the change that removed `queries` from `browserslist` object: https://github.com/ai/browserslist/commit/640b62fa83a20897cae75298a9f2715642531623#diff-168726dbe96b3ce427e7fedce31bb0bcL465

**Comment by MoOx** [comment]
Can you please bump browserlist version to make this PR complete? Thanks!

**Comment by phil-r** [comment]
@MoOx done 😉

**Comment by Nyalab** [comment]
this was fixed by #71, thanks for your time though

**Pull request closed without merging**
