### PR TITLE
Explicit requires

### PR DESCRIPTION
**Pull request by tiagocpontesp**
See https://github.com/Nyalab/caniuse-api/issues/40

### CODE REVIEW

**Comment by MeoMix** [comment]
I'd just like to follow-up on this and mention that this PR is riding on the tail of previous PRs intended to increase JSPM's support for deps which use caniuse-db (ref: https://github.com/postcss/autoprefixer/issues/618 and https://github.com/postcss/autoprefixer/pull/619)

**Comment by MoOx** [comment]
What is the issue here? I don't understand what this code is changing.

**Comment by MeoMix** [comment]
Heh. @tiagocpontesp I think you just shifted code around rather than removing a line of code.

The intent was to remove the logic which removes ".json" file endings. There's nothing wrong with being explicit (as far as I'm aware!) and it confuses JSPM which assumes ".js" if there's no file ending.

**Comment by tiagocpontesp** [comment]
hey, the code does what it's supposed to: it keeps the json file endings.

**Comment by MeoMix** [comment]
@tiagocpontesp But nothing in the code actually changed...? Instead of two map calls (replace JSON file ending, return require statement) the code is now just a single map call, but it does both those things. So.. it's the same?

**Comment by tiagocpontesp** [comment]
It is changed! Did you try to run it?

The `.replace('.json','')` is only being run against `const feature` (like what was previously there) -- which is the export's name.
The `file` function parameter remains unchanged, with the json extension.

**Comment by MeoMix** [comment]
**Oh!** I see it now. The `return` statement has both `feature` and `file` in it where `file` still has the `.json` ending. Cool :+1:

**Comment by tiagocpontesp** [comment]
Thanks for the quick reply. I was getting uncomfortable trying to lyrically describe such a small piece of code haha

**Comment by tiagocpontesp** [comment]
BumpBump. Test fail unrelated. And this is still a hindrance.

**Comment by alexisvincent** [comment]
@MoOx Would love to see this change merged. Will help a lot with jspm users wanting to use postcss.

**Comment by Nyalab** [comment]
Close in favour of #43

**Pull request closed without merging**
