### PR TITLE
cache node packages on appveyor and travis

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @Nyalab

**Comment by Nyalab** [comment]
thanks for your PR, what purpose does it serve? isn't the cache regenerated for each branch?

**Comment by thijstriemstra** [comment]
@Nyalab there's no need to re-download these packages everytime, NPM is slow enough as it is. I was hoping this would speed up the build and prevent some unnecessary downloads.

**Comment by thijstriemstra** [comment]
@Nyalab what do you think?

**Comment by thijstriemstra** [comment]
ping @Nyalab

**Pull request closed without merging**
