### PR TITLE
Use the original `lodash` npm package

### PR DESCRIPTION
**Pull request by koistya**
Ref #31

### CODE REVIEW

**Comment by ben-eb** [comment]
I wouldn't advise this course of action. This change will bloat the download size of caniuse-api and all of its dependent modules, and doesn't add anything positive in return. If the problem is an outdated dependency, the dependency should be updated.

**Comment by MoOx** [comment]
This looks like a edge case issue with your setup since travis is ok.

**Comment by koistya** [comment]
@ben-eb are you kidding :) This npm package even with full `lodash` version weighs just 4KB archived (.tgz) and 10KB unarchived.

**Comment by MoOx** [comment]
Anyway, it looks like a bug from a small lodash module that doesn't have the right dependency.

**Comment by koistya** [comment]
This package including all its dependencies weights 17MB (unarchived). When `lodash.uniq` and `lodash.memoize` are replaced with the full `lodash` version, it will weight 19MB. Not a significant increase in size, IMHO.

**Comment by MoOx** [comment]
That's not my point. You are not fixing a bug here, just avoiding to trigger it. We should better fix it for real :)

**Comment by koistya** [comment]
I have tested it. Updating `lodash.uniq` from `3.1.0` to `3.9.3` (`lodash/array/uniq`) fixes the problem with `Error: Cannot find module 'lodash._basebind'`. Ref cssnext/cssnext#151

**Comment by MoOx** [comment]
1.3.2 should fix that.

**Pull request closed without merging**
