### PR TITLE
Use simple require for feature list

### LINKED ISSUE #18: allow in browser usage
it might sound silly, according to the database weight, but it would be nice to replace `require.resolve` usage by a json generation to avoid the readDir.
Probably hooked in the postinstall to have a json that match the installed db (so no prepublish since the json might be outdated according to the caniuse-db (hello semver)).
Also hooked in the "pretest" and it should be good.
Well it's almost done. I'll take a look to that tomorrow morning if nobody had done that before me.

### PR DESCRIPTION
**Pull request by MoOx**
Should fix #18.
This also include a little commit to handle #19 until we get a real solution.

### CODE REVIEW

**Comment by Nyalab** [comment]
looks good to me, if you can just fix the tests, it would be awesome :ok_hand:

**Comment by MoOx** [comment]
Seems fixed. I used a tricky trick, but should be good enough. That said this will probably break on windows env.  This 6to5 thing for publishing is annoying. Maybe we should handle this package with io.js which is doing this automatically (es6 to 5 on files directly), don't you think ?

**Comment by Nyalab** [comment]
Hmmm, this is a good idea, not now, but it could be nice.

**Comment by Lhokhilloo** [comment]
> Colaborador

Yeah

**Pull request merged**
