### PR TITLE
Fix #29

### LINKED ISSUE #29: Silent fail on postInstall
The postInstall scripts seems to never be executed.
it fails leaving stderout with

```
> caniuse-api@1.3.1 postinstall d:\E-Ressources\WebApps\www\node_modul
es\gulp-cssnext\node_modules\cssnext\node_modules\caniuse-api
> node -e "require('shelljs/global');if(test('-d', 'dist'))exec('node
dist/generate-features.js')"
```

https://github.com/Nyalab/caniuse-api/commit/d1b2d11e37a4738221349034cbefee640b081212#commitcomment-10753523

### PR DESCRIPTION
**Pull request by pl12133**
Check if we are running as a `node_module`, otherwise use `__dirname/dist`.

### CODE REVIEW

**Comment by pl12133** [comment]
I'm not sure if the tests are correct as it seems unrelated to this pull, I just fixed them to pass.

**Comment by MoOx** [comment]
Can you explain your logic? I am not sure to follow the issue here.

**Comment by pl12133** [comment]
When installing `caniuse-api` as a dependency, it will fail in the post-install step because it searches for an improper relative path. It will look for `./dist`, and when running in the context of the installing package that will resolve to `/home/user/myproject/dist`; but it should be looking for `/home/user/myproject/node_modules/caniuse-api/dist`. So I made a change that will try to find the `dist` directory instead of using just `./dist`.

```js
var dist = '';
try {
    // use require.resolve to find the `caniuse-api` module, this will resolve to:
    // /home/user/myproject/node_modules/caniuse-api/dist/index.js
    // path.dirname will turn that into:
    // /home/user/myproject/node_modules/caniuse-api/dist/
    dist = path.dirname(require.resolve('caniuse-api'));
} catch (e) {
    // if we cannot resolve the path of `caniuse-api` as a module then it is being installed standalone
    dist = path.join(__dirname, 'dist');
}
```

**Comment by MoOx** [comment]
Sorry but the current logic is working propery... And for lots of user (89,569 downloads in the last month - without any complains every day). It's used in widely used project like cssnext (as a dependency) so I am not sure this kind of changes are required. If you have an issue that might be related to your node/npm version. What is your node & npm versions?

**Comment by pl12133** [comment]
I understand you don't want to disrupt the user base with a change so if this is specific to my environment I can continue checking. Here's my versions, same as TravisCI:

```sh
[root@localhost ~]# nvm --version
0.31.2
[root@localhost ~]# node --version
v6.3.0
[root@localhost ~]# npm --version
3.10.3
```

**Comment by MoOx** [comment]
You versions looks good. Indead that might be related to your env. Can you bring more materials? OS, docker? etc... In generator.js, cwd should be the node module itself (that's why test(-d, dist) is working for most people.

**Comment by pl12133** [comment]
No docker, Arch Linux environment:
```sh
[root@localhost inhouse-component-module]# uname -a
Linux localhost 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux
```

Our module uses a build module. That build module is using `"postcss-cssnext": "^2.7.0"` which pulls in `"caniuse-api": "^1.3.2"`. This error doesn't happen to others on Node <6. So the results of NPM list:

```sh
inhouse-component-module@1.0.0
├─┬ inhouse-build-module@1.0.0
│ ├─┬ postcss-cssnext@2.7.0
│ │ ├─┬ caniuse-api@1.5.0
```

There must be some differences in path behavior somewhere. This might become a more critical issue if others begin upgrading to Node >6, but for now I'll keep looking into how Node/NPM deals with path resolutions.

**Comment by MoOx** [comment]
Han indeed. I am still stuck with node 5 for many reasons. v6 might be the reason :/

**Comment by pl12133** [comment]
I'll keep investigating, thanks for the help and feel free to close if this doesn't fit the projects goals (maybe you are already removing the generation step).

**Pull request closed without merging**
