### PR TITLE
Removed generation step. Require directly from caniuse-db

### PR DESCRIPTION
**Pull request by alexisvincent**
This passes the tests... I assume its equivalent to before

### CODE REVIEW

**Comment by alexisvincent** [comment]
Fixes #42

**Comment by MoOx** [comment]
Thank you so much for this. I will add some comment since I would like an option for "sort of" backward compat.

**Comment by MoOx** [comment]
Oh! I am seeing that caniuse now provides all data in a single json. That's cool and new (this file did not exist in the past).

I guess we should bump caniuse-db version to be sure data.json exist.

According to the change, does not look like a breaking change... Do you think we can release this as a patch? poke @Nyalab

**Comment by alexisvincent** [comment]
Yeah, didn't think it did.

**Comment by alexisvincent** [comment]
@MoOx Whether its a patch or not, do you think you could attempt to release a version of cssnext that uses this? Means I can close a bunch of issues all over the place :)

**Comment by MoOx** [comment]
@alexisvincent if it is released as a patch, this will be automatic for postcss-cssnext. If merged as a breaking change, I will have to bump, but yeah, I will do that if it's required.

As this merge/release could impact a lot of projects according to the number of download, I will wait to have some free times around (not a good idea a Friday afternoon) to cut a release, so if any major problems (or even minor) came up I can handle it quickly.

Again, thanks for taking time to handle this, I really appreciate the help!

**Comment by alexisvincent** [comment]
My pleasure. Thanks for the really tight feedback loop. Makes contributing easy. I just read through the entire codebase. Logic is sound. But found one features array access i didn't change (no test coverage). Everything is clean now. And is definitely not a breaking change.

**Comment by Nyalab** [comment]
can we test this on a small sized VM, to see if the perfs are not horrible? i'm afraid loading in memory all the db can make this step horribly long, but if it does not, we can release this as a patch @MoOx

**Comment by alexisvincent** [comment]
I can help with this if you'd like. Can run a docker container on my machine if that's ok with you?

Kind regards
Alexis




On Mon, Aug 29, 2016 at 10:20 AM +0200, "Sébastien Balayn" <notifications@github.com> wrote:












can we test this on a small sized VM, to see if the perfs are not horrible? i'm afraid loading in memory all the db can make this step horribly long, but if it does not, we can release this as a patch @MoOx

**Comment by MoOx** [comment]
Lgtm

**Comment by MoOx** [comment]
@alexisvincent any update for the test in a slow env?

**Comment by alexisvincent** [comment]
Haven't had time yet. But will hopefully do it this afternoon. Unless one of you would like to.

**Comment by alexisvincent** [comment]
@MoOx I tested on google's f1-micro (1 shared vcpu, 600mb ram). Basically just `time node list/index.js`. Original had an average of 105ms, new one had an average of 112ms. So I think it's safe to say this is good to merge.

**Comment by MoOx** [comment]
@alexisvincent This is awesome. Will merge and release as a patch on monday morning! Thank you for your patience and involvement.

**Comment by alexisvincent** [comment]
👍

**Comment by Nyalab** [comment]
Thank you @alexisvincent & @MoOx

**Comment by MoOx** [comment]
Released as 1.5.2 \o/

**Pull request merged**
