### PR TITLE
Migrate from caniuse-db to caniuse-lite. Closes #57.

### LINKED ISSUE #57: Migrate to caniuse-lite.
Hi @Nyalab!

[I've been working on an unofficial way to consume caniuse support data](https://github.com/ben-eb/caniuse-lite) that is intended for modules, whereas the official dataset is intended for people. So I dropped a lot of keys that Autoprefixer & Browserslist don't use and then compacted the rest of the data. The end result weighs around 7 times less than the official database as of this writing, and the only downside is a slight performance hit when the data is restored into a caniuse format. We optimised for size, not speed, but I think we can perhaps improve this further in the future. For now the dataset is as close to caniuse-db as possible, for easy migration.

* https://travis-ci.org/postcss/autoprefixer/jobs/219404429 - caniuse-db
* https://travis-ci.org/postcss/autoprefixer/jobs/220033486 - caniuse-lite

So I think it's important to use a single source of truth for the support data, and as I am starting to make much more use of caniuse-api I'd like to update the module to use caniuse-lite too.

My only reservation about the migration is that you are using the `title` key from each feature. I'd like to know if that can be dropped so that we can keep caniuse-lite as lean as possible. But I would like some input from caniuse-api users, on whether they think this is necessary or not. I'm open to any feedback! 😄 

Copying in users of this module/caniuse data: @agauniyal, @una, @schiehll, @sylvainpolletvillard, @moox, @bebraw & @ai.

Thanks!

### PR DESCRIPTION
**Pull request by ben-eb**
I recommend a major version bump for this patch. Let me know if you have any queries or suggestions! 😃 

Edit: It might be worth waiting for Browserslist 2 before releasing. poke @ai

### CODE REVIEW

**Comment by ben-eb** [comment]
With Browserslist 2, we only have one test failure:

https://github.com/Nyalab/caniuse-api/blob/master/test/index.js#L32

<details>
  <summary>The function receives this list of browsers.</summary>
    ie 5.5
    ie 6
    ie 7
    ie 8
    ie 9
    ie 10
    ie 11
    edge 12
    edge 13
    edge 14
    edge 15
    firefox 2
    firefox 3
    firefox 3.5
    firefox 3.6
    firefox 4
    firefox 5
    firefox 6
    firefox 7
    firefox 8
    firefox 9
    firefox 10
    firefox 11
    firefox 12
    firefox 13
    firefox 14
    firefox 15
    firefox 16
    firefox 17
    firefox 18
    firefox 19
    firefox 20
    firefox 21
    firefox 22
    firefox 23
    firefox 24
    firefox 25
    firefox 26
    firefox 27
    firefox 28
    firefox 29
    firefox 30
    firefox 31
    firefox 32
    firefox 33
    firefox 34
    firefox 35
    firefox 36
    firefox 37
    firefox 38
    firefox 39
    firefox 40
    firefox 41
    firefox 42
    firefox 43
    firefox 44
    firefox 45
    firefox 46
    firefox 47
    firefox 48
    firefox 49
    firefox 50
    firefox 51
    firefox 52
    firefox 53
    chrome 4
    chrome 5
    chrome 6
    chrome 7
    chrome 8
    chrome 9
    chrome 10
    chrome 11
    chrome 12
    chrome 13
    chrome 14
    chrome 15
    chrome 16
    chrome 17
    chrome 18
    chrome 19
    chrome 20
    chrome 21
    chrome 22
    chrome 23
    chrome 24
    chrome 25
    chrome 26
    chrome 27
    chrome 28
    chrome 29
    chrome 30
    chrome 31
    chrome 32
    chrome 33
    chrome 34
    chrome 35
    chrome 36
    chrome 37
    chrome 38
    chrome 39
    chrome 40
    chrome 41
    chrome 42
    chrome 43
    chrome 44
    chrome 45
    chrome 46
    chrome 47
    chrome 48
    chrome 49
    chrome 50
    chrome 51
    chrome 52
    chrome 53
    chrome 54
    chrome 55
    chrome 56
    chrome 57
    safari 3.1
    safari 3.2
    safari 4
    safari 5
    safari 5.1
    safari 6
    safari 6.1
    safari 7
    safari 7.1
    safari 8
    safari 9
    safari 9.1
    safari 10
    safari 10.1
    opera 9
    opera 9.5-9.6
    opera 10.0-10.1
    opera 10.5
    opera 10.6
    opera 11
    opera 11.1
    opera 11.5
    opera 11.6
    opera 12
    opera 12.1
    opera 15
    opera 16
    opera 17
    opera 18
    opera 19
    opera 20
    opera 21
    opera 22
    opera 23
    opera 24
    opera 25
    opera 26
    opera 27
    opera 28
    opera 29
    opera 30
    opera 31
    opera 32
    opera 33
    opera 34
    opera 35
    opera 36
    opera 37
    opera 38
    opera 39
    opera 40
    opera 41
    opera 42
    opera 43
    opera 44
    ios_saf 3.2
    ios_saf 4.0-4.1
    ios_saf 4.2-4.3
    ios_saf 5.0-5.1
    ios_saf 6.0-6.1
    ios_saf 7.0-7.1
    ios_saf 8
    ios_saf 8.1-8.4
    ios_saf 9.0-9.2
    ios_saf 9.3
    ios_saf 10.0-10.2
    ios_saf 10.3
    op_mini all
</details>

How would you like me to proceed?

**Comment by ben-eb** [comment]
Any updates, guys? Unfortunately this is currently a blocker for me; I'm happy to do the work but I need some direction on how I should update these tests to pass (or if it is still worth keeping this unit test).

Thanks!

**Comment by MoOx** [comment]
@ben-eb It seems you fixed the issue? I don't see any problem on this PR right now.

**Comment by ben-eb** [comment]
@MoOx When I wrote the PR, Browserslist 2 was not released, so when I tried adding it I got that test failure noted above. So I am wondering how this test should be updated; I didn't write it initially so I am not sure what it is there for. :smile:

**Comment by Nyalab** [comment]
Please just make the test pass by editing the regex. This is not used internally, this is for exporting the list of all supported browsers (a feature that was asked but not used internally yet).

**Comment by ben-eb** [comment]
@Nyalab Done! 👍

**Comment by ben-eb** [comment]
Thanks!

**Pull request merged**
