### PR TITLE
Fix postinstall hook for Windows

### PR DESCRIPTION
**Pull request by MoOx**
Maybe we should provide this as a script, but since it’s short, I think
we can like that for now.

### CODE REVIEW

**Comment by MoOx** [comment]
This Should Work™ and will add full Windows compatibility for cssnext :)
I guess you can release that as patch ;)

**Comment by Nyalab** [comment]
thanks but #23 was a more complete one :smile:

**Comment by MoOx** [comment]
Not at all. #23 is a regression :/

**Comment by MoOx** [comment]
Ready to merge

**Comment by Nyalab** [comment]
thanks !

**Pull request merged**
